name: "Setup"
author: "eth-p"
description: "A reusable action for setting up linting jobs."

inputs:
  node_auth_token:
    description: "The GITHUB_TOKEN"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v3.5.0
      with:
        node-version-file: ".nvmrc"
        registry-url: 'https://npm.pkg.github.com'
        scope: 'sfusurge'
        token: "${{ inputs.node_auth_token }}"

    - name: Install full build tools
      if: ${{ inputs.minimal != 'true' }}
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node_auth_token }}
        NODE_AUTH_TOKEN_GITHUB: ${{ inputs.node_auth_token }}
      run: |
        echo "==> Installing Build Tools"
        npm install
