name: Building

on:
  pull_request: {}

jobs:
  prettier:
    name: "Build Dry Run"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Build
        run: |
          npm run build
