name: Linting

on:
  pull_request: {}
  push: {}

jobs:
  prettier:
    name: "Check Formatting"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          minimal: true
          install_formatters: true
      
      - name: Check
        run: |
          npm run format -- --check

  eslint:
    name: "Check Lints"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          minimal: true
          install_linters: true
      
      - name: Check
        run: |
          npm run lint -- --output-file=eslint_report.json --format=json || status=$?
          if [ "$status" -eq 2 ]; then exit 2; fi

      - name: Annotate
        uses: ataylorme/eslint-annotate-action@v2
        if: ${{ always() }}
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
          fail-on-warning: true
          check-name: Problems
