name: Linting

on:
  pull_request: {}
  push: {}

jobs:
  prettier:
    name: "Check Formatting"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          minimal: true
          install_formatters: true
      
      - name: Check
        run: |
          npm run format -- --check
